DROP TABLE STUDENT;
CREATE TABLE STUDENT
(
	SNO VARCHAR2(5) PRIMARY KEY,
	NAME VARCHAR2(32),
	KOR NUMBER CHECK(KOR BETWEEN 0 AND 100),
	ENG NUMBER CHECK(ENG BETWEEN 0 AND 100),
	MAT NUMBER CHECK(MAT BETWEEN 0 AND 100),
	AVE NUMBER(5,2),
	GRADE CHAR(1)
);
