DROP TABLE BOARD;
DROP TABLE MEMBER;

-- 회원 테이블
CREATE TABLE MEMBER
(
	NO NUMBER,
	ID VARCHAR2(32) NOT NULL UNIQUE,
	PW VARCHAR2(32) NOT NULL,
	NAME VARCHAR2(50),
	EMAIL VARCHAR2(200) NOT NULL UNIQUE,
	REGDATE DATE
);

-- 게시판 테이블
CREATE TABLE BOARD
(
	IDX NUMBER,
	AUTHOR VARCHAR2(50),
	TITLE VARCHAR2(2000) NOT NULL,
	CONTENT VARCHAR2(4000),
	HIT NUMBER,
	POSTDATE DATE
);

-- 기본키
ALTER TABLE MEMBER ADD CONSTRAINT MEMBER_PK PRIMARY KEY(NO);
ALTER TABLE BOARD ADD CONSTRAINT BOARD_PK PRIMARY KEY(IDX);
-- 외래키
ALTER TABLE BOARD ADD CONSTRAINT BOARD_MEMBER_PK FOREIGN KEY(AUTHOR) REFERENCES MEMBER(ID);

-- 시퀀스
DROP SEQUENCE MEMBER_SEQ;
DROP SEQUENCE BOARD_SEQ;
CREATE SEQUENCE MEMBER_SEQ INCREMENT BY 1 START WITH 1 NOCYCLE NOCACHE;
CREATE SEQUENCE BOARD_SEQ INCREMENT BY 1 START WITH 1 NOCYCLE NOCACHE;